language: objective-c  
osx_image: xcode8.1
xcode_workspace: one/one.xcworkspace
xcode_scheme: one
xcode_sdk: iphonesimulator10.1
script:
  - xcodebuild clean build -sdk iphonesimulator -workspace one/one.xcworkspace -scheme one CODE_SIGNING_REQUIRED=NO
